SET HEADING OFF ECHO OFF FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 1000
SPOOL cleandb_script.sql

SELECT 'EXEC DBMS_JOB.REMOVE(' || JOB || ');' FROM USER_JOBS;
SELECT 'DROP TRIGGER ' || TRIGGER_NAME || ';' FROM USER_TRIGGERS;
SELECT 'DROP PACKAGE ' || OBJECT_NAME || ';' FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE';
SELECT 'DROP PROCEDURE ' || OBJECT_NAME || ';' FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PROCEDURE';
SELECT 'DROP FUNCTION ' || OBJECT_NAME || ';' FROM USER_OBJECTS WHERE OBJECT_TYPE = 'FUNCTION';
SELECT 'DROP VIEW ' || VIEW_NAME || ';' FROM USER_VIEWS;
SELECT 'DROP SEQUENCE ' || SEQUENCE_NAME || ';' FROM USER_SEQUENCES;
SELECT 'DROP TABLE ' || TABLE_NAME || ' CASCADE CONSTRAINTS;' FROM USER_TABLES;
SELECT 'DROP CLUSTER ' || OBJECT_NAME || ';' FROM USER_OBJECTS WHERE OBJECT_TYPE = 'CLUSTER';
SELECT 'DROP DATABASE LINK ' || DB_LINK || ';' FROM USER_DB_LINKS;

SPOOL OFF
SET LINESIZE 100
SET PAGESIZE 24
SET HEADING ON ECHO ON FEEDBACK ON

SET ECHO OFF
